
app_name="群组社交"#成功

#结果集
SUCCESS="0"#成功
FAIL="1"#失败
EXCEPTION="-1"#异常


USEREXIST="10000"#用户已经存在
FILENOLEGAL="10001"#文件不合法
VINT="10002"#验证未通过
UNUSEREXIST="10003"#用户不存在
OLDPWDFAIL="10004"#旧密码输入错误

DIARYDEAL_NOTSEND=1#用户未完成处理
DIARYDEAL_NOTRECEIVE=2#商家未完成接收
DIARYDEAL_NOTRESPONSE=3#商家接收到未反应
DIARYDEAL_NOTDONE=4#商家反应订单未完成
DIARYDEAL_BACK=5#订单完成，派送中
DIARYDEAL_DONE=6#交易结束
DIARYDEAL_RESPONSE_BAD=7#商家拒单
DIARYDEAL_DO_NULL=8#客户取消订单

DIANCAN_XIANCHANG=1#现场点餐
DIANCAN_YUDING=2#预定点餐
DIANCAN_WAIMAI=3#外卖点餐

CHATUSER_TYPE_SEND=1#主动发送引起的聊天
CHATUSER_TYPE_RECEIVE=2#被动接收引起的聊天
CHATUSER_TYPE_QUN=3#群聊



USER_NORMAL=0#普通用户，不能创建群组
USER_VIP=1#高级用户，能创建群组


publicfinalstaticStringPUSH_NO="0"#不需要点击的
publicfinalstaticStringPUSH_NEW_DIARY="1"#有新的日志
publicfinalstaticStringPUSH_NEW_USER="2"#有新的用户加入
publicfinalstaticStringPUSH_NEW_SIXIN="3"#有新的私信
publicfinalstaticStringPUSH_NEW_TONGZHI="4"#有新的通知
publicfinalstaticStringPUSH_NEW_LIUYAN="5"#有新的留言
publicfinalstaticStringPUSH_NEW_QUNLIAO="6"#有新的群聊
publicfinalstaticStringPUSH_NEW_DEALDIARY="7"#新订单

#聊天用户的状态
CHATUSER_NEW=1#聊天关系有新信息
CHATUSER_OLD=2#聊天关系没有新信息
CHATUSER_HIDE=3#聊天关系隐藏


CONTENT_TYPEWORD=0#只包含文字的内容
CONTENT_TYPEIMG=1#包含图片的内容
CONTENT_TYPEVIDEO=2#包含视频的内容
CONTENT_TYPEURL=3#包含链接的内容
CONTENT_CAIDAN_WORD=4#菜单无图片
CONTENT_CAIDAN_IMG=5#菜单有图片

MESSAGE_TYPE_SIXIN=1#私信
MESSAGE_TYPE_LIUYAN=2#留言
MESSAGE_TYPE_TONGZHI=3#通知
MESSAGE_TYPE_USER=4#聊天用户
MESSAGE_TYPE_USER_LIUYAN=5#用户留言
MESSAGE_TYPE_QUN_LIUYAN=6#群留言

#1表示收藏日志2表示举报日志3表示日志置顶4分享日志5赞6赞赏
DIARY_SHOUCANG=1
DIARY_JUBAO=2
DIARY_ZHIDING=3
DIARY_SHARE=4
DIARY_ZAN=5
DIARY_MONEY=6
DIARY_TUIJIAN=7
DIARY_GUANZHU=8

#0表示全群可见未审核1表示日志仅自己可见2表示全群可见审核通过3表示全群可见审核未通过
DIARY_INIT=0
DIARY_JUST_ME=1
DIARY_OK=2
DIARY_NOT=3
DIARY_OUT=4#日志以过时宝贝已售

#1表示举报用户2表示屏蔽3表示关注4表示用户拉入黑名单5用户点赞
USER_JUBAO=11
USER_PINGBI=12
USER_GUANZHU=13
USER_LAHEI=14
USER_ZAN=15
USER_SHOUCANG=16
USER_TUIJIAN=17

#0表示用户和日志都不需要审核1表示用户需要审核2表示日志需要审核3表示用户日志都需要审核4群成员不能发表日志用户不用审核，5群成员不能发表日志用户要审核，
QUN_NOT=0
QUN_USER=1
QUN_DIARY=2
QUN_USER_DIARY=3
QUN_USER_DIARY_NOT=4
QUN_USER_DIARY_NOT_USER=5

#下面的不同群类型，表示不同的用途
QUNUSETYPE1=1#二手平台群
QUNUSETYPE2=2#名片夹群平台群
QUNUSETYPE3=3#精品专栏群平台群

#1表示举报群2表示屏蔽群
QUN_JUBAO=21
QUN_PINGBI=22
QUN_SHOUCANG=23
QUN_ZHIDING=24
QUN_MONEY=25
QUN_TUIJIAN=26
QUN_ZAN=27

#1表示群主2表示辅助管理员3成员4未审核成员5用户审核未通过
USERQUN_QUNZHU=1
USERQUN_FUZHU=2
USERQUN_YUAN=3
USERQUN_NOT=4
USERQUN_CANT=5


maxqunnum=20