var EXAMPLES=[
    //{id:"scatter-anscombe-quartet",title:"散点图回归线",type:"scatter"},
    {id:"scatter-aqi-color",title:"颜色，明暗，大小，多维数据虚拟映射(可用)",type:"scatter"},   //有用
    {id:"scatter-large",title:"大规模散点图(可用)",type:"scatter"},
    {id:"scatter-map-brush",title:"地图，散点，覆盖选中(可用)",type:"scatter"},
    {id:"scatter-map",title:"地图，散点，颜色虚拟映射(可用)",type:"scatter"},
    {id:"bubble-gradient",title:"气泡图(可用)",type:"scatter"},
    {id:"effectScatter-bmap",title:"全国主要城市空气质量 - 百度地图(可用)",type:"scatter"},
    {id:"effectScatter-map",title:"全国主要城市空气质量(可用)",type:"scatter"},
    {id:"scatter-weibo",title:"大规模散点地图(可用)",type:"scatter"},
   // {id:"scatter-life-expectancy-timeline",title:"各国人均寿命与GDP关系演变",type:"scatter"},
    {id:"scatter-matrix",title:"Scatter Matrix",type:"parallel"},
   // {id:"scatter-nutrients",title:"Scatter Nutrients",type:"scatter"},
    //{id:"scatter-painter-choice",title:"Master Painter Color Choices Throughout History",type:"scatter"},
    {id:"scatter-polar-punchCard",title:"极坐标散点图(可用)",type:"scatter"},
    {id:"scatter-punchCard",title:"直角坐标系散点图（可用）",type:"scatter"},
    {id:"scatter-single-axis",title:"单轴散点图(可用)",type:"scatter"},
    {id:"scatter-weight",title:"男性女性身高体重分布(可用)",type:"scatter"},
    {id:"scatter-world-population",title:"世界地图颜色大小双映射(可用)",type:"scatter"},
    //{id:"scatter-nutrients-matrix",title:"Scatter Nutrients Matrix",type:"scatter"},
    {id:"area-rainfall",title:"时间轴，双y轴，面积图（可用）",type:"line"},
    {id:"area-simple",title:"时间轴大数据量面积图（可用）",type:"line"},
    {id:"area-stack",title:"堆叠区域图（可用）",type:"line"},
    {id:"bar-animation-delay",title:"柱状图动画延迟（可用）",type:"bar"},
    {id:"bar-brush",title:"柱状图框选（可用）",type:"bar"},
    {id:"bar-gradient",title:"渐变色 阴影 点击缩放（可用）",type:"bar"},
    {id:"bar-negative",title:"正负条形图（可用）",type:"bar"},
    {id:"bar-negative2",title:"交错正负轴标签（可用）",type:"bar"},
    {id:"bar-stack",title:"堆叠柱状图（可用）",type:"bar"},
    {id:"bar-tick-align",title:"坐标轴刻度与标签对齐（可用）",type:"bar"},
    {id:"bar-waterfall",title:"深圳月最低生活费组成（可用）",type:"bar"},
    {id:"bar-waterfall2",title:"阶梯瀑布图（可用）",type:"bar"},
    {id:"bar-y-category-stack",title:"堆叠条形图（可用）",type:"bar"},
    {id:"bar-y-category",title:"世界人口总量 - 条形图（可用）",type:"bar"},
    {id:"bar1",title:"某地区蒸发量和降水量（可用）",type:"bar"},
    {id:"boxplot-light-velocity",title:"Boxplot Light Velocity",type:"boxplot"},
    {id:"boxplot-light-velocity2",title:"Boxplot Light Velocity2",type:"boxplot"},
    {id:"boxplot-multi",title:"Multiple Categories",type:"boxplot"},

    {id:"candlestick-brush",title:"Candlestick Brush",type:"candlestick"},
    {id:"candlestick-sh-2015",title:"2015 年上证指数",type:"candlestick"},
    {id:"candlestick-sh",title:"上证指数",type:"candlestick"},
    {id:"candlestick-touch",title:"触屏上的坐标轴指示器",type:"candlestick"},
   // {id:"confidence-band",title:"Confidence Band",type:"line"},
    {id:"dynamic-data",title:"动态数据",type:"bar"},
   // {id:"dynamic-data2",title:"动态数据 + 时间坐标轴",type:"line"},

   // {id:"funnel-align",title:"漏斗图(对比)",type:"funnel"},
    {id:"funnel-customize",title:"漏斗图（可用）",type:"funnel"},
    //{id:"funnel-mutiple",title:"漏斗图",type:"funnel"},
    {id:"funnel",title:"漏斗图（可用）",type:"funnel"},
    {id:"gauge-car-dark",title:"Gauge Car Dark（可用）",type:"gauge"},
    {id:"gauge-car",title:"Gauge Car（可用）",type:"gauge"},
    {id:"gauge",title:"Gauge（可用）",type:"gauge"},
    {id:"geo-lines",title:"模拟迁徙（可用）",type:"map"},
    {id:"graph-circular-layout",title:"Les Miserables",type:"graph"},
    {id:"graph-force",title:"力引导布局",type:"graph"},
   // {id:"graph-force2",title:"力引导布局",type:"graph"},
    //{id:"graph-grid",title:"笛卡尔坐标系上的 Graph",type:"graph"},
    {id:"graph-life-expectancy",title:"Graph Life Expectancy",type:"graph"},
    {id:"graph-npm",title:"NPM Dependencies",type:"graph"},
   // {id:"graph-simple",title:"Graph 简单示例",type:"graph"},
    {id:"graph-webkit-dep",title:"Graph Webkit Dep",type:"graph"},
    {id:"graph",title:"Les Miserables",type:"graph"},
    {id:"grid-multiple",title:"双坐标系，相同横轴（可用）",type:"line"},
    {id:"heatmap-bmap",title:"热力图与百度地图扩展（可用）",type:"heatmap"},
    {id:"heatmap-cartesian",title:"笛卡尔坐标系上的热力图（可用）",type:"heatmap"},
    {id:"heatmap-large-piecewise",title:"热力图 - 颜色的离散映射（可用）",type:"heatmap"},
    {id:"heatmap-large",title:"热力图 - 2w 数据（可用）",type:"heatmap"},
    {id:"heatmap-map",title:"全国主要城市空气质量（可用）",type:"heatmap"},
    {id:"line-aqi",title:"纵轴分段颜色显示（可用）",type:"line"},
    {id:"line-draggable",title:"拖动修改数据节点（可用）",type:"line"},
   // {id:"line-easing",title:"Line Easing",type:"line"},
    //{id:"line-log",title:"对数轴示例",type:"line"},
    {id:"line-marker",title:"多数据，标记线，标记点（可用）",type:"line"},
    {id:"line-pen",title:"点击添加数据节点（可用）",type:"line"},
    //{id:"line-polar",title:"极坐标双数值轴",type:"line"},
    {id:"line-polar2",title:"极坐标双数值轴（可用）",type:"line"},
    //{id:"line-sections",title:"一天用电量分布",type:"line"},
    {id:"line-stack",title:"折线图堆叠（可用）",type:"line"},
    {id:"line-step",title:"阶梯图(可用)",type:"line"},
    //{id:"line-y-category",title:"Line Y Category",type:"line"},
    {id:"multiple-x-axis",title:"多 X 轴示例（可用）",type:"line"},
  //  {id:"line-tooltip-touch",title:"Tooltip and DataZoom on Mobile",type:"line"},
    {id:"lines-airline",title:"65k+ 飞机航线",type:"map"},
    {id:"lines-bmap-bus",title:"北京公交路线 - 百度地图",type:"map"},
    {id:"lines-bmap-effect",title:"北京公交路线 - 线特效",type:"map"},
    {id:"lines-bmap",title:"杭州热门步行路线 - 百度地图",type:"map"},
    {id:"map-china-dataRange",title:"iphone销量（可用）",type:"map"},
    {id:"map-china",title:"Map China（可用）",type:"map"},
    {id:"map-HK",title:"香港地图数据颜色虚拟映射（可用）",type:"map"},
   // {id:"map-locate",title:"Map Locate",type:"map"},
   // {id:"geo-map-scatter",title:"map and scatter share a geo",type:"map"},
    //{id:"map-parallel-prices",title:"Prices and Earnings 2012",type:"scatter"},
    {id:"map-province",title:"34 省切换查看（可用）",type:"map"},
    {id:"map-usa",title:"美国地图数据颜色虚拟映射（可用）",type:"map"},
    {id:"map-world-dataRange",title:"世界地图数据颜色虚拟映射（可用）",type:"map"},
    {id:"map-world",title:"世界地图（可用）",type:"map"},

    {id:"mix-line-bar",title:"折柱混合（可用）",type:"bar"},
    //{id:"mix-timeline-finance",title:"2002全国宏观经济指标",type:"bar"},
    {id:"mix-zoom-on-value",title:"Mix Zoom On Value（可用）",type:"bar"},
    {id:"multiple-y-axis",title:"多 Y 轴示例（可用）",type:"bar"},
    {id:"parallel-aqi",title:"Parallel Aqi",type:"parallel"},
    {id:"parallel-nutrients",title:"Parallel Nutrients",type:"parallel"},
    {id:"pie-custom",title:"Customized Pie（可用）",type:"pie"},
    {id:"pie-doughnut",title:"环形图（可用）",type:"pie"},
    {id:"pie-nest",title:"嵌套环形图（可用）",type:"pie"},
    //{id:"pie-pattern",title:"饼图纹理",type:"pie"},
    {id:"pie-roseType",title:"南丁格尔玫瑰图（可用）",type:"pie"},
    {id:"pie-simple",title:"某站点用户访问来源（可用）",type:"pie"},
    {id:"radar-aqi",title:"AQI - 雷达图（可用）",type:"radar"},
    //{id:"radar-custom",title:"自定义雷达图",type:"radar"},
    //{id:"radar-multiple",title:"多雷达图",type:"radar"},
    {id:"radar",title:"基础雷达图（可用）",type:"radar"},
    //{id:"radar2",title:"浏览器占比变化",type:"radar"},
    {id:"sankey-energy",title:"Sankey Diagram",type:"sankey"},
    {id:"sankey-product",title:"Sankey Diagram",type:"sankey"},

    {id:"treemap-disk",title:"Disk Usage",type:"treemap"},
    {id:"treemap-drill-down",title:"ECharts 配置项查询分布",type:"treemap"},
    {id:"treemap-obama",title:"How $3.7 Trillion is Spent",type:"treemap"},
    {id:"treemap-visual",title:"Gradient Mapping",type:"treemap"},
   // {id:"watermark",title:"水印 - ECharts 下载统计",type:"bar"},
    {id:"pictorialBar-hill",title:"圣诞愿望清单和山峰高度",type:"pictorialBar"},
    {id:"pictorialBar-velocity",title:"驯鹿的速度",type:"pictorialBar"},
    {id:"pictorialBar-vehicle",title:"交通工具",type:"pictorialBar"},
    {id:"pictorialBar-spirit",title:"精灵",type:"pictorialBar"},
    {id:"pictorialBar-body-fill",title:"人体含水量",type:"pictorialBar"},
    {id:"pictorialBar-dotted",title:"虚线柱状图效果",type:"pictorialBar"},
    {id:"pictorialBar-forest",title:"森林的增长",type:"pictorialBar"},
    {id:"themeRiver-basic",title:"主题河流图（可用）",type:"themeRiver"},
    {id:"themeRiver-lastfm",title:"ThemeRiver Lastfm（可用）",type:"themeRiver"},
    {id:"calendar-graph",title:"Calendar Graph",type:"graph"},
    {id:"calendar-pie",title:"Calendar Pie",type:"calendar"},
    //{id:"calendar-effectscatter",title:"Calendar Effectscatter",type:"scatter"},
   // {id:"calendar-vertical",title:"Calendar Heatmap Vertical",type:"heatmap"},
    //{id:"calendar-horizontal",title:"Calendar Heatmap Horizontal",type:"heatmap"},
    {id:"calendar-effectscatter",title:"Calendar Effectscatter",type:"calendar"},
    {id:"calendar-vertical",title:"Calendar Heatmap Vertical",type:"calendar"},
    {id:"calendar-horizontal",title:"Calendar Heatmap Horizontal",type:"calendar"},
    {id:"calendar-charts",title:"Calendar Charts",type:"calendar"},
    {id:"calendar-lunar",title:"Calendar Lunar",type:"calendar"}],

    CHART_TYPES={
        scatter:"散点图",
        line:"折线图",
        bar:"柱状图",
        map:"地图",
        pie:"饼图",
        radar:"雷达图",
        candlestick:"k线图",
        boxplot:"箱线图",
        heatmap:"热力图",
        graph:"关系图",
        treemap:"矩形树图",
        parallel:"平行坐标",
        sankey:"桑基图",
        funnel:"漏斗图",
        gauge:"仪表盘",
        pictorialBar:"象形柱图",
        themeRiver:"主题河流图",
        calendar:"日历图"
    };


