# Generated by Django 2.0.2 on 2018-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetype', models.IntegerField()),
                ('contenttype', models.IntegerField()),
                ('send_id', models.IntegerField()),
                ('receive_id', models.IntegerField()),
                ('abid', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('imgone', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['id'],
            },
        ),
    ]
