# Generated by Django 2.0.2 on 2018-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('send_id', models.IntegerField(default=0)),
                ('receive_id', models.IntegerField(default=0)),
                ('abid', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chatuser',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='contenttype',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='messagetype',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='receive_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='send_id',
            field=models.IntegerField(default=0),
        ),
    ]
