# Generated by Django 2.0.2 on 2018-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180305_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='messagetype',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='imgone',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
